class DataIngestitionArtifact :...
class DataValidationArtifact :...
class DataTransformationArtifact :...
class ModelTrainerArtifact:...
class ModelEvaluationArtifact:...
class ModelPusherArtifact :...
