from dataclasses import dataclass

@dataclass
class DataIngestionArtifact:
    pass


class DataValidationArtifact :...
class DataTransformationArtifact :...
class ModelTrainerArtifact:...
class ModelEvaluationArtifact:...
class ModelPusherArtifact :...
